version: '3.8'

services:
  chrome:
    image: selenium/standalone-chrome:4.1.0
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "4441:4444"
      - "7900:7900"

  firefox:
    image: selenium/standalone-firefox:4.1.0
    hostname: firefox
    privileged: true
    shm_size: 2g
    ports:
      - "4442:4444"
      - "7901:7900"